### PR TITLE
Fixed ALSA

### PR DESCRIPTION
**Pull request by Gandalf098**
Added Path Binding to ALSA, to make sure alsa works under snap

### CODE REVIEW

**Comment by iGeek098** [comment]
trying to fix this error:

--2020-02-14 18:30:52--  https://r1---sn-uxaxjvhxbt2u-5atr.googlevideo.com/videoplayback?expire=1581719439&ei=L8tGXsPeNpStxN8PpauhmAc&ip=156.205.252.14&id=o-AI1O2jyCiMRu55Gd0aHtQC03ReFnPSctXJyB1bG3wno2&itag=251&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-uxaxjvhxbt2u-5atr%2Csn-hgn7rn7r&ms=au%2Crdu&mv=m&mvi=0&pl=18&initcwndbps=176250&vprv=1&mime=audio%2Fwebm&gir=yes&clen=4219727&dur=253.981&lmt=1581258825461238&mt=1581697729&fvip=1&keepalive=yes&fexp=23842630&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRQIhAKRCkAUhxrueyUQYfw8FhrtBT2g0Bk57sdua1oQoXmQxAiAvf2Omqc1oILx7ySLEP3-ED1FHgwNfh9fvtyytqsHizQ%3D%3D&sig=ALgxI2wwRQIhAPLguEiu728I-iTEqn9kqkt-FMGHueZXlCFoPY2JJqVeAiAA3BxAV_mClTePYh28TYnwtqXC9Q5-SwfqoppLxHstsQ==&ratebypass=yes
Resolving r1---sn-uxaxjvhxbt2u-5atr.googlevideo.com (r1---sn-uxaxjvhxbt2u-5atr.googlevideo.com)... 
[file] Reading from stdin...

213.158.160.44

Connecting to r1---sn-uxaxjvhxbt2u-5atr.googlevideo.com (r1---sn-uxaxjvhxbt2u-5atr.googlevideo.com)|213.158.160.44|:443... 
connected.

HTTP request sent, awaiting response... 
200 OK
Length: 4219727 (4.0M) [audio/webm]
Saving to: ‘STDOUT’


     0K ........
.. ......
 (+) Audio --aid=1 --alang=eng (*) (opus 2ch 48000Hz)

ALSA lib conf.c:3916:(snd_config_update_r) Cannot access file /usr/share/alsa/alsa.conf
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM default
[ao/alsa] Playback open error: No such file or directory

[ao/oss] Can't open audio device /dev/dsp: No such file or directory

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel

jack server is not running or cannot be started

JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
[ao/jack] cannot open server
[ao] Failed to initialize audio driver 'jack'

Could not open/initialize audio device -> no sound.
Audio: no audio
.... .......... .......... ........
..  1%  677K 6s
    50K ........
.. ....
...... .........
.
 ........
.. ......
....  2% 1.84M 4s
   100K ..
........ ..
........
 ........
.. .......... ....


......  3% 2.12M 3s
   150K ..
........
 ........
.. ......
.... ....
...... ..
........  4% 1.94M 3s

   200K ........
.. ......
.... ....
...... ..........
 ..........  6% 2.43M 3s
   250K .
.....
.... ........
.. ..
........

**Comment by iGeek098** [comment]
sorry, solved by enabling "play and record sound" permissions from software manager

**Comment by keshavbhatt** [comment]
was "play and record sound" permission disabled by default for olivia ??? :flushed:

**Comment by iGeek098** [comment]
ahhmm..., well yeah idk how 🙃

**Pull request closed without merging**
